export enum ROUTES {
    ROOT = '/',
    SERVICES = '#services',
    ABOUT = '#about',
    APPLICATION = '#application',
    STAGES = '#stages',
    REVIEWS = '#reviews',
    QUESTIONS = '#questions',
    CONTACTS = '#contacts',
    APPEAL_SUCCESS = '/appeal',
    PAYMENT_FROM = '/payment',
    PAYMENT_SUCCESS = '/payment-complete',
    AUTO = '/auto',
    BANKS = '/banks',
    CIVIL = '/civil',
    CONSTRUCTION = '/construction',
    CONSUMER = '/consumer',
    ESTATE = '/estate',
    FAMILY = '/family',
    FRAUD = '/fraud',
    INSURANCE = '/insurance',
    LAND = '/land',
    TAXES = '/taxes',
    WORK = '/work',
}
